{
    "name": "Custom Approvals",
    "version": "1.0.0",
    "author": "Aneeqa Baig",
    "depends": ["base", "hr", "website" ],
    "data": [
        # 'views/approval_views.xml',
        "security/ir.model.access.csv",
        # 'views/hello_template.xml',
        # 'views/force_password_template.xml',
        "views/custom_approvals.xml",
        # "views/res_user_views.xml",
        "views/welcome_page.xml",
        # "views/profile.xml",
        "views/services.xml",
        "views/compliants.xml",
        "views/profile_shell.xml",
        # "views/res_user_views.xml",
        "views/profile_tabs.xml",
        "views/profile_sidebar.xml",
        "views/hello_template.xml",
        # "views/force_password_template.xml",
        "views/custom_approvals.xml",
        "views/tab_notifications.xml",
        "views/welcome_page.xml",
        "views/tab_services.xml",
        "views/tab_personal.xml",
        "views/personal_info.xml",
        "views/services_block.xml",
        "views/notifications_block.xml",
        "views/request_history.xml",
        "views/approvals_dashboard.xml",
        "views/new_request_form.xml",
        "views/profile_shell_layout.xml"
        ],
        

    "installable": True,
    "application": False,
}
