{
    'name': 'HRMIS Core',
    'version': '1.0',
    'summary': 'Automatically installs core Odoo modules for my organization.',
    'description': "",
    'category': 'Administration',
    'author': '',
    'website': '',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'account',
        'crm',
        'website',
        'purchase',
        'hr',
        'project',
        'ohrms_holidays_approval',
        # 'custom_approvals_odoo18',
    ],
    'data': [],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}